server:
  port: 9202
zuul:
  host:
    connect-timeout-millis: 3000
    socket-timeout-millis: 3000
  ignoredPatterns:
    - /oauth/**
    - /actuator/**
    - /test/**
  routes:
    admin-api:
      path: /**
      url: http://localhost:3000

#logging:
#  level:
#    org.springframework.web: trace
#    org.springframework.security: trace
management:
  endpoints:
    web:
      exposure:
        include: "*"